define graylog::input::gelf_http(
  Enum['present','absent']  $ensure                    = 'present',
  String                    $bind_address              = '0.0.0.0',
  Integer                   $decompress_size_limit     = '8 MB'.to_bytes,
  Boolean                   $enable_cors               = true,
  Integer                   $idle_writer_timeout       = 60,
  Integer                   $max_chunk_size            = 65536,
  Optional[String]          $override_source           = undef,
  Stdlib::Port              $port                      = 12280,
  Integer                   $recv_buffer_size          = '1 MB'.to_bytes,
  Enum['global','local']    $scope                     = 'global',
  Boolean                   $tcp_keepalive             = false,
  String                    $tls_cert_file             = '',
  String                    $tls_client_auth           = 'disabled',
  String                    $tls_client_auth_cert_file = '',
  Boolean                   $tls_enable                = false,
  String                    $tls_key_file              = '',
  String                    $tls_key_password          = '',
){
  graylog_input { $name:
    ensure        => $ensure,
    type          => 'org.graylog2.inputs.gelf.http.GELFHttpInput',
    scope         => $scope,
    configuration => {
      bind_address              => $bind_address,
      decompress_size_limit     => $decompress_size_limit,
      enable_cors               => $enable_cors,
      idle_writer_timeout       => $idle_writer_timeout,
      max_chunk_size            => $max_chunk_size,
      override_source           => $override_source,
      port                      => $port,
      recv_buffer_size          => $recv_buffer_size,
      tcp_keepalive             => $tcp_keepalive,
      tls_cert_file             => $tls_cert_file,
      tls_client_auth           => $tls_client_auth,
      tls_client_auth_cert_file => $tls_client_auth_cert_file,
      tls_enable                => $tls_enable,
      tls_key_file              => $tls_key_file,
      tls_key_password          => $tls_key_password,
    },
  }
}