name: Validate
on: [push]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3.1
          bundler-cache: true

      - name: Run Linter
        run:  bundle exec rake
