name: Validate
on: [push]
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: docker run --rm -w /src -v $GITHUB_WORKSPACE:/src puppet/pdk:latest validate
